runtime: go125
instance_class: F1
default_expiration: "1m"
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.7

handlers:
  - url: /api/.*
    script: auto
  - url: /
    static_files: web/dist/index.html
    upload: web/dist/index.html
  - url: /(.*)
    static_files: web/dist/\1
    upload: web/dist/.*
